alias g="git"
alias pull="git pull"
alias push="git push"
alias stash="git stash --include-untracked"
alias apply="git stash apply"
alias applypatch="git apply --reject --whitespace=fix"
alias merge="git merge"
alias checkout="git checkout"
alias sw="git switch"
alias switch="git switch -"
alias rebase="git rebase"
alias cherry="git cherry-pick"
alias amend="git commit -a --amend"
alias commit="git commit -m"